services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - codebin-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=codebin
      - POSTGRES_PASSWORD=codebin123
      - POSTGRES_DB=codebin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - codebin-network

volumes:
  postgres_data:

networks:
  codebin-network:
    driver: bridge